tasks:
  - name: terraform
    before: |
      ./bin/terraform_cli_install   
      cp $PROJECT_ROOT/terraform.tfvars.example $PROJECT_ROOT/terraform.tfvars
      source /bin/.project.env   
  - name: sinatra
    before: | 
      cd $PROJECT_ROOT
      cd terratowns_mock_server
      bundle install
      bundle exec ruby server.rb     
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
     ./bin/aws_cli_install
  - name: http-server 
    before: |
     npm install --global http-server 
    command: 
      http-server   
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
    - phil294.git-log--graph
